### ISSUE TITLE
Id operator en réponse du signin

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage-api#25]
En se connectant en tant qu'opérateur, on ne récupère pas l'id de l'opérateur à stocker dans la session. C'est utile pour le module déclaratif.

**Comment by jonathanfallon** [comment]
Il y a une propriété `operator` qui te donne son ID. Si tu as des cas où cette propriété est vide ou absente, c'est sûrement un bug.

**Comment by samueleyre** [comment]
C'est bon !
