### ISSUE TITLE
Filtre par date ne fonctionne pas avec tous les formats en base  

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage-api#34]
Beaucoup de dates ne sont pas au même format. Ex : 2019-02-39 10:51:57+0200 et 2018-03-02T17:33:17Z ou  2018-04-02T18:22:12.173Z

Le format n'est peut-être pas assez précis, on pourrait imposer YYYY-MM-DDTHH:mm:ss.sssZ ou bien regarder du côté back si on peut améliorer les requêtes par dates.

La requête en front est faite avec le format YYYY-MM-DDTHH:mm:ss.sssZ

**Comment by jonathanfallon** [comment]
Les dates ne sont pas converties correctement au format UTC lors de leur sauvegarde dans la base.
1. Utiliser un `set` dans le schema pour convertir la date :heavy_check_mark: 
2. Migrer les dates existantes vers le bon format
