### ISSUE TITLE
Les opérateurs admin n'ont pas l'autorisation d'uploader 

### ISSUE THREAD

**Issue by samueleyre** [betagouv/preuve-covoiturage-api#36]
permission : journey.import

TODO
1. Check des permissions dans une routine de déploiement `yarn fix-permissions`
2. Comparaison des permissions de l'utilisateur avec les nouvelles
3. Appliquer la modif si diff

**Comment by jonathanfallon** [comment]
Les permissions modifiées en config ne sont pas encore appliquées au déploiement. C'est possible de les réappliquer en sauvegardant le profile utilisateur dans l'interface (même si ce n'est pas optimal)
