### ISSUE TITLE
Modification du Schema financier des trajets

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage-api#43]
Après un rapide sondage auprès des opérateurs sur 2 propositions de schémas pour collecter les informations financières des trajets (couples passager-conducteur), le schéma suivant a été choisi : 

- `driver.cost` : Frais engagés - somme perçue par le conducteur (incitation de l'opérateur par exemple)
- `driver.incentive` : Incitation donnée par l'AOM au conducteur
- `driver.remaining_fee` : somme restante à charge du conducteur (calculé par le Registre)
- `passenger.cost` : Participation du passager / nombre de sièges réservés - somme perçue par le passager (si incitation du passager)
- `passenger.incentive` : Incitation donnée par l'AOM au passager
- `passenger.remaining_fee` : somme restante à charge du passager (calculé par le Registre)

`remaining_fee = cost - incentive`

```
driver
  cost *
  incentive *
  remaining_fee **
passenger
  cost *
  incentive *
  remaining_fee **

*  envoyé par l'opérateur
** calculé par le registre
```

Les valeurs par défaut sont toutes de 0 et la borne minimum de 0.

**Comment by margot-sanchez** [comment]
Je ne suis pas d'accord à 100%. Les 3 informations que l'on doit collecter par l'opérateur sont : 
- Nombre siège réservé “passenger.seats” : Nombre de sièges réservés par l'occupant passager. 
- Participation du passager “passenger.cost” : Coût du service pour l’occupant passager après incitation opérateur (subventions, promotions, etc).
- Somme perçue par le conducteur “driver.amount_collected” (ou tout autre nom) : La somme perçue par le conducteur, comprenant la participation des passager, une possible incitation opérateur (subventions, promotions, etc) et prise de commission de l’opérateur. 

Le Registre calcule lui : 
- Frais engagés du conducteur “driver.cost” (ou on peut le renommer si cela va pas) : Frais engagés par le conducteur selon le barème kilométrique (0,552 euros  / km).

Avec ces 4 variables tu peux jouer pour calculer le reste à charge. 

Pourquoi tu considères que c'est l'opérateur qui communique l'incitation AOM ? C'est pour le schéma de simulation ? 
Pourquoi tu demandes à l'opérateur de faire participation/nombre siège ? C'est pas plus simple de le faire nous ?

**Comment by jonathanfallon** [comment]
Nombre siège réservé “passenger.seats” : 
Participation du passager “passenger.cost” : Coût du service pour l’occupant passager après incitation opérateur (subventions, promotions, etc).
Somme perçue par le conducteur “driver.amount_collected” : La somme perçue par le conducteur, comprenant la participation des passager, après une possible incitation opérateur (subventions, promotions, etc) et prise de commission de l’opérateur. 

### Envoyé par l'opérateur
- `passenger.seats` : Nombre de sièges réservés par l'occupant passager.
- `passenger.cost` : Participation du passager / nombre de sièges réservés - somme perçue par le passager (si incitation du passager)
- `driver.amount_collected` : La somme perçue par le conducteur, comprenant la participation des passager, après une possible incitation opérateur (subventions, promotions, etc) et prise de commission de l’opérateur.

## Calculé par le registre

- `driver.cost` : Frais engagés - somme perçue par le conducteur (incitation de l'opérateur par exemple)
- `driver.incentive` : Incitation donnée par l'AOM au conducteur
- `driver.remaining_fee` : somme restante à charge du conducteur (calculé par le Registre)
- `passenger.incentive` : Incitation donnée par l'AOM au passager
- `passenger.remaining_fee` : somme restante à charge du passager (calculé par le Registre)

`remaining_fee = cost - incentive`

```
driver
  amount_collected
  cost
  incentive
  remaining_fee
passenger
  cost
  seats
  incentive
  remaining_fee
```

**Comment by margot-sanchez** [comment]
J'ai MAJ le schéma JSON https://registre-preuve-de-covoiturage.gitbook.io/produit/api/schema-json
