### ISSUE TITLE
Mystère de la base de données 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage-api#47]
![image](https://user-images.githubusercontent.com/15428433/54762909-4b113380-4bf5-11e9-8db0-56f239d73ca8.png)
15000 trajets "safe"

Au même moment dans la base
![image](https://user-images.githubusercontent.com/15428433/54762929-56fcf580-4bf5-11e9-83aa-f43a88fbded0.png)
11 000 trajets.

Où sont passés les 4000 trajets.

Indice il n'y a plus de trajets dans la base depuis le 13 mars.

**Comment by jonathanfallon** [comment]
Dans l'ancien schéma de base, nous n'avions pas l'ID opérateur (sur 4000 trajets). Ces trajets ne passent pas l'algo de construction des trajets qui sont listés dans l'interface. Ce problème est visible seulement en `staging`.
